BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = 
USER_LIB_PATH = /home/alumno/Descargas/Bare-Arduino-Project-master/lib/
ARDUINO_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
include /usr/share/arduino/Arduino.mk